version: '3'

services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db-mysql:
        condition: service_healthy
    
  db-mysql:
    image: mysql:latest
    container_name: "test-mysql-db"
    # restart: always
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "db"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=root --password=password -e 'show databases'
      # timeout: 20s
      # retries: 10